src/UserBundle/Entity/User.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: kmitad
 * Date: 04/07/2017
 * Time: 16:16
 */

namespace UserBundle\Entity;


use AppBundle\Entity\Traits\IdEntity;
use ApplicationBundle\Entity\StaffApplication;
use ApplicationBundle\Entity\StaffDocument;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Entity\User as BaseUser;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class User
 * @package UserBundle\Entity
 * @ORM\Entity()
 * @ORM\Table(name="users")
 */
class User extends BaseUser
{
    const RATE_DAILY = 'DAILY';
    const RATE_HOURLY = 'HOURLY';

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $lastname;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $phone;

    /**
     * @var StaffDocument[]
     *
     * @ORM\OneToMany(targetEntity="ApplicationBundle\Entity\StaffDocument", mappedBy="user", orphanRemoval=true)
     */
    protected $documents;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $rateType;

    /**
     * @var float
     *
     * @ORM\Column(type="float", options={"default": 0})
     */
    protected $rate = 0;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $comments;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param string $lastname
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    public function getDisplayName()
    {
        $name = $this->name;

        if ($this->lastname) {
            $name .= ' ' . $this->lastname;
        }

        return $name;
    }

    /**
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * @return StaffDocument[]
     */
    public function getDocuments()
    {
        return $this->documents;
    }

    /**
     * @param StaffDocument[] $documents
     */
    public function setDocuments($documents)
    {
        $this->documents = $documents;
    }

    /**
     * @return string
     */
    public function getRateType()
    {
        return $this->rateType;
    }

    /**
     * @param string $rateType
     */
    public function setRateType($rateType)
    {
        $this->rateType = $rateType;
    }

    /**
     * @return float
     */
    public function getRate()
    {
        return $this->rate;
    }

    /**
     * @param float $rate
     */
    public function setRate($rate)
    {
        $this->rate = $rate;
    }

    /**
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param string $comments
     */
    public function setComments($comments)
    {
        $this->comments = $comments;
    }

    /**
     * @param Request $request
     * @return User
     */
    public function fromRequest(Request $request)
    {
        $this->setEmail($request->get('email'));
        $this->setPhone($request->get('phone'));
        $this->setRateType($request->get('rate_type'));
        $this->setRate($request->get('rate'));
        $this->setComments($request->get('comments'));
        $name = explode(' ', $request->get('fullname'));
        $this->setName($name[0]);
        if (count($name) > 1) {
            $this->setLastname($name[1]);
        }
        $this->setUsername($request->get('email'));
        return $this;
    }
}

src/UserBundle/Controller/DefaultController.php
<?php

namespace UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('UserBundle:Default:index.html.twig');
    }
}

src/UserBundle/Resources/views/admin/template/users/edit.template.html.twig
{% extends '@Admin/layout/app.layout.html.twig' %}
{% block main %}
    <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
            <section id="horizontal-form-layouts">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title" id="horz-layout-basic">Add Item</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-body collapse in">
                                <div class="card-block">
                                    <form class="form form-horizontal" method="POST">
                                        <div class="form-body">
                                            <h4 class="form-section"><i class="ft-user"></i> General Information</h4>
                                            <div class="form-group row">
                                                <label class="col-md-3 label-control" for="name">Name</label>
                                                <div class="col-md-9">
                                                    <input type="text" id="name" class="form-control" placeholder="Name" name="name" value="{{ item.name }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-md-3 label-control" for="lastname">Surname</label>
                                                <div class="col-md-9">
                                                    <input type="text" id="lastname" class="form-control" placeholder="Surname" name="lastname" value="{{ item.lastname }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-md-3 label-control" for="email">Email</label>
                                                <div class="col-md-9">
                                                    <input type="text" id="email" class="form-control" placeholder="Email" name="email" value="{{ item.email }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-md-3 label-control" for="password">Password</label>
                                                <div class="col-md-9">
                                                    <input type="text" id="password" class="form-control" placeholder="Password" name="password" value="{{ item.plainPassword }}">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-md-3 label-control" for="role">Role</label>
                                                <div class="col-md-9">
                                                    <select type="text" id="role" class="form-control" name="role">
                                                        <option value="ROLE_USER" {% if item.hasRole('ROLE_USER') %}selected{% endif %}>User</option>
                                                        <option value="ROLE_ADMIN" {% if item.hasRole('ROLE_ADMIN') %}selected{% endif %}>Admin</option>
                                                        <option value="ROLE_SUPER_ADMIN" {% if item.hasRole('ROLE_SUPER_ADMIN') %}selected{% endif %}>Super Admin</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-actions">
                                            <a href="{{ url('app_admin_section_list', {'section': section}) }}">
                                                <button type="button" class="btn btn-warning mr-1">
                                                    <i class="ft-x"></i> Cancel
                                                </button>
                                            </a>
                                            <button type="submit" class="btn btn-primary">
                                                <i class="fa fa-check-square-o"></i> Save
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

src/UserBundle/Resources/views/admin/template/users/list.template.html.twig
{% extends '@Admin/layout/app.layout.html.twig' %}
{% block main %}
    <div class="content-wrapper">
        <div class="content-header row"></div>
        <div class="content-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">{{ caption }}</h4>
                            <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a href="{{ url('app_admin_section_add', {'section': section}) }}"><i class="ft-plus"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body collapse in">
                            <div class="card-block card-dashboard">
                                <p>Manage Users here</p>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="bg-primary">
                                    <tr>
                                        <th>#</th>
                                        <th>Username</th>
                                        <th>Display name</th>
                                        <th>Roles</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in items %}
                                    <tr>
                                        <th scope="row">{{ loop.index }}</th>
                                        <td>{{ item.username }}</td>
                                        <td>{{ item.displayName }}</td>
                                        <td>{{ item.roles | join(',') }}</td>
                                        <td>
                                            <a href="{{ url('app_admin_section_edit', {'section': section, 'id': item.id}) }}">
                                                <div class="btn btn-success btn-sm"><i class="ft-edit"></i> Edit</div>
                                            </a>
                                            <a href="{{ url('app_admin_section_delete', {'section': section, 'id': item.id}) }}">
                                                <div class="btn btn-danger btn-sm"><i class="ft-trash-2"></i> Delete</div>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}